### ISSUE TITLE
Linux App -hanging

### ISSUE THREAD

**Issue by muriloime** [josiahsrc/voquill#15]
Tried install with .deb and AppImage. The app opens ( with the system trying to close it for the first time, but if you stick to it, it opens ), and then it hangs on loading wheel .   This is the log: 

Voquill
=== Voquill Startup ===
[startup] Version: 0.1.0
[startup] OS: linux
[startup] Arch: x86_64
[startup] Building Tauri application...
[app] Starting application setup...
[gpu] Enumerating GPUs...
[gpu] Found: Intel(R) UHD Graphics 630 (CFL GT2) (Vendor: Intel [0x8086], Device: 0x3E9B, Type: IntegratedGpu, Backend: Vulkan)
[gpu] Found: NVIDIA GeForce RTX 2060 (Vendor: NVIDIA [0x10DE], Device: 0x1F11, Type: DiscreteGpu, Backend: Vulkan)
[gpu] Found: llvmpipe (LLVM 15.0.7, 256 bits) (Vendor: Unknown [0x10005], Device: 0x0000, Type: Cpu, Backend: Vulkan)
[gpu] Found: Mesa Intel(R) UHD Graphics 630 (CFL GT2) (Vendor: Intel [0x8086], Device: 0x0000, Type: IntegratedGpu, Backend: Gl)
[gpu] Successfully enumerated 4 GPU(s)
[diagnostics] Startup diagnostics written to: /home/murilo/.local/share/com.voquill.desktop/logs/startup_diagnostics.log
[whisper] Attempting to enumerate Vulkan devices...
ggml_vulkan: Found 1 Vulkan devices:
ggml_vulkan: 0 = NVIDIA GeForce RTX 2060 (NVIDIA) | uma: 0 | fp16: 1 | bf16: 1 | warp size: 32 | shared memory: 49152 | int dot: 1 | matrix cores: NV_coopmat2
[whisper] Successfully enumerated 1 Vulkan device(s)
[whisper] Attempting GPU inference on 'NVIDIA GeForce RTX 2060' (ID: 0, ≈6.00 GiB free VRAM)
whisper_init_from_file_with_params_no_state: loading model from '/home/murilo/.local/share/com.voquill.desktop/models/ggml-base.bin'
whisper_init_with_params_no_state: use gpu    = 1
whisper_init_with_params_no_state: flash attn = 0
whisper_init_with_params_no_state: gpu_device = 0
whisper_init_with_params_no_state: dtw        = 0
whisper_init_with_params_no_state: devices    = 2
whisper_init_with_params_no_state: backends   = 2
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 512
whisper_model_load: n_audio_head  = 8
whisper_model_load: n_audio_layer = 6
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 512
whisper_model_load: n_text_head   = 8
whisper_model_load: n_text_layer  = 6
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 2 (base)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: n_langs       = 99
whisper_model_load:      Vulkan0 total size =   147.37 MB
whisper_model_load: model size    =  147.37 MB
[whisper] GPU initialised successfully on 'NVIDIA GeForce RTX 2060'
=== Voquill Startup ===
[startup] Version: 0.1.0
[startup] OS: linux
[startup] Arch: x86_64
[startup] Running in keyboard listener mode

Would love if you can shed some light 

many thanks

**Comment by josiahsrc** [comment]
Thanks for reporting @muriloime . My first guess is that it might be hanging on trying to interop with your GPU (I see some NVIDIA logs in there). We'll take a look and see what could be going on cc @MichaelWGibson

**Comment by josiahsrc** [comment]
@muriloime From what I can piece together, it looks like auth is hanging on your device due to an issue with index db. I have a patch fix to address this, could you download .deb image from the latest dev release and see if it fixes the issue for you? https://github.com/josiahsrc/voquill/releases/tag/desktop-dev-v0.0.190

**Comment by muriloime** [comment]
Hi @josiahsrc  , thanks . I managed to start the app now, but it still does not transcribe  ( i am testing in the app) . 


=== Voquill Startup ===
[startup] Version: 0.1.0
[startup] OS: linux
[startup] Arch: x86_64
[startup] Running in keyboard listener mode
[gpu] Enumerating GPUs...
[gpu] Found: AMD Radeon 890M Graphics (RADV GFX1150) (Vendor: AMD [0x1002], Device: 0x150E, Type: IntegratedGpu, Backend: Vulkan)
[gpu] Found: llvmpipe (LLVM 19.1.1, 256 bits) (Vendor: Unknown [0x10005], Device: 0x0000, Type: Cpu, Backend: Vulkan)
[gpu] Found: AMD Radeon 890M Graphics (radeonsi, gfx1150, LLVM 19.1.1, DRM 3.64, 6.17.4-76061704-generic) (Vendor: AMD [0x1002], Device: 0x0000, Type: Other, Backend: Gl)


I am on pop os 24.04 , wayland

**Comment by josiahsrc** [comment]
Progress! Ok, I think I found the issue (at least with the next failure). Could you try out 0.0.193? https://github.com/josiahsrc/voquill/releases/tag/desktop-dev-v0.0.193

**Comment by josiahsrc** [comment]
@muriloime Quick update: I pushed these changes to prod: If you're on the stable release version, you should have the fixes there as well. Let me know if that works for you and we'll go ahead and close this issue. Thanks!

**Comment by muriloime** [comment]
@josiahsrc  thanks. I 've got passed the last error , but got a new one 

<img width="660" height="410" alt="Image" src="https://github.com/user-attachments/assets/73ebe6e9-cd06-4428-9ca2-6295a6fc1e93" />


Maybe this helps: 


whisper_model_load: model size    =  147.37 MB
[whisper] GPU initialised successfully on 'NVIDIA GeForce RTX 2060'
=== Voquill Startup ===
[startup] Version: 0.1.0
[startup] OS: linux
[startup] Arch: x86_64
[startup] Running in keyboard listener mode
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dsnoop.c:540:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream

ALSA lib pcm_pulse.c:758:(pulse_prepare) PulseAudio: Unable to create stream: Timeout

[recording] failed to build stream for 'default': stream build: A backend-specific error has occurred: ALSA function 'snd_pcm_prepare' failed with error 'I/O error (5)'
[recording] using input device 'samplerate' via host Alsa
whisper_backend_init_gpu: no GPU found
whisper_init_state: kv self size  =    6.29 MB
whisper_init_state: kv cross size =   18.87 MB
whisper_init_state: kv pad  size  =    3.15 MB
whisper_init_state: compute buffer (conv)   =   16.28 MB
whisper_init_state: compute buffer (encode) =   85.88 MB
whisper_init_state: compute buffer (cross)  =    4.66 MB
whisper_init_state: compute buffer (decode) =   96.37 MB
[whisper] using language code: Some("en")
whisper_full_with_state: input is too short - 90 ms < 100 ms. consider padding the input audio with silence

**Comment by josiahsrc** [comment]
😆 That meme 👌 @muriloime Is it crashing for you or did that one work? I definitely see some error logs in there, but I'm hoping that we're handling those.

**Comment by muriloime** [comment]
No, still not working, There is a problem with mic ( working fine on other apps). I think that is a peoblem with bridge alsa - pipewire , and that'swhy we are seeing these logs

**Comment by josiahsrc** [comment]
@muriloime Been looking into what's going wrong. It looks like Voquill is defaulting to use a virtual device on your machine. It's hard to confirm this is the real issue since I don't have your environment, though. Would you have a second to try running this branch on your machine locally? We might have more success that way since you can run it natively on your device  https://github.com/josiahsrc/voquill/pull/18 

Another thing you can try if you haven't already, there's a microphone settings option in the settings page where you can choose your microphone. If you open that, I wonder if you'd see the wrong device being selected

<img width="1012" height="722" alt="Image" src="https://github.com/user-attachments/assets/d7d062eb-1d0d-4663-ba3a-d15b25765558" />

**Comment by josiahsrc** [comment]
I looked into this again. I think this was an issue with the selected microphone not actually being used for recording. Pushing up a fix for this, will go ahead and close that other PR

**Comment by josiahsrc** [comment]
@muriloime I'm going to go ahead and close this issue. Feel free to reopen if this isn't working for you. And thanks again for working with me on this

**Comment by muriloime** [comment]
Thanks @josiahsrc . Still no luck , I ended up letting it go , as I don't have the time ATM. Thanks anyway

**Comment by josiahsrc** [comment]
Darn. Well thanks for working with me on this one @muriloime . If you ever want to try again let me know and we can reopen
