### ISSUE TITLE
Won't launch on Win 10

### ISSUE THREAD

**Issue by nigelp** [josiahsrc/voquill#6]
Icon just disappears from view on taskbar. Nada.

**Comment by josiahsrc** [comment]
Oh shoot, thanks for raising. I'll look into it

**Comment by MormonOne** [comment]
Same but I am running windows 11 with an AMD GPU.

**Comment by josiahsrc** [comment]
This should be fixed. Fee free to reopen if you're still seeing the issue. Thanks!

**Comment by nigelp** [comment]
Nah, sorry it still doesn't work. At least the icon appears this time, but fails to launch and now just hangs. Uninstalled.

**Comment by josiahsrc** [comment]
Darn, thanks for the heads up. cc @MichaelWGibson may know more

**Comment by MichaelWGibson** [comment]
Yeah, this is tricky because I don't have a way to reproduce locally. I found a friend with an AMD graphics card on Windows reporting similar symptoms. It works for him if he runs it with `VOQUILL_WHISPER_DISABLE_GPU=1`. I'll keep digging. 

As a mitigation, it might make sense to lazy-initialize GPUs (Maybe a "detect GPUs button") so users who want to use an API key or CPU don't have to deal with this.

**Comment by josiahsrc** [comment]
@MichaelWGibson I think I remember you added in lazy init? Is it possible that this should be fixed now? I just checked linux, and it seems to work great, can't confirm on a GPU-less windows machine, though.

**Comment by josiahsrc** [comment]
@MichaelWGibson pushed up a fix that should fix this issue. I confirmed that this is working on my Windows computer that doesn't have a GPU. Voquill booted up and ran without any issues. @MormonOne @nigelp sorry for the delay here, could you check to see if this fixes the issue for you on the latest version?

**Comment by nigelp** [comment]
@josiahsrc sorry still  no go. Doesn't hang now, just tries to load and disappears when you click the icon.

**Comment by josiahsrc** [comment]
@nigelp Thanks for trying that out. I think we've got this figured out now. I downloaded Windows 10 on my computer, booted it up, and tried Voquill with the latest changes, and it works now on that machine. I think if you give it one more try, it should work.

**Comment by nigelp** [comment]
I'm very sorry, it's still not working. It installs and then immediately disappears from the task tray and when I click on the desktop icon, the window just shuts down instantly.  Could this be because I'm installing it into a custom folder and not the default?

**Comment by josiahsrc** [comment]
Dang. @nigelp Do you see any errors show up when it crashes, or does it just disappear? It could be due to a custom folder. And you're installing the latest version too?

**Comment by nigelp** [comment]
@josiahsrc nope no errors, just instant disappear. and yes the very latest version.

**Comment by MichaelWGibson** [comment]
I'm pretty sure this commit (now deployed) fixes the problem. 

 https://github.com/josiahsrc/voquill/commit/8cd32643f0cf7bc2feaa0a31ce79f1ce90da028a

**Comment by nigelp** [comment]
I'm really sorry to say that I've tried it again and it still fails.  Each time it seems to last longer though, this time it lasted about three seconds.  I saw the splash screen with the account sign up and button, etc.  But then it just disappears and that's it and the icon in the tray disappears as well. Goodness knows where they go. I also tried installing both the MSI as well as the EXE this time, and I tried wiping everything off my disc which had the word "voquill" in it.  Still no joy. There's something really weird going on.

**Comment by josiahsrc** [comment]
@nigelp I would like to try one more thing if you're up for it (sorry to keep bothering you about this)

So we published this release that is a CPU-only distribution of Voquill. I'm curious if you try it out if this one works for you. My fingers are crossed, at this point I'm grasping at straws. But let's see. 🤞 

https://github.com/josiahsrc/voquill/releases/tag/desktop-dev-v0.0.321

**Comment by nigelp** [comment]
![Image](https://github.com/user-attachments/assets/1d4982c9-7ba0-466d-a01d-c381ae0258d8)
Yep, that worked fine. So it must be a CUDA problem. If I had to guess maybe it's because my i7-8700 CPU is AVX2 compatible and not AVX-512?

**Comment by josiahsrc** [comment]
That is FANTASTIC news. Yeah, it must be something with Vulkan. I'm not sure exactly where it went wrong, but it's proven quite hard to bundle both CPU and GPU support in the same client. So I think that might have been the issue. We're going to start shipping a GPU version and a CPU version to avoid this problem. That's kind of the best path we have forward right now. Thank you for trying that out!!

**Comment by josiahsrc** [comment]
Marking this as done. Will ship this in the next prod release once I sort out the release strategy
